server:
  port: 8607

spring:
  jmx:
    default-domain: mogu-gateway
  application:
    name: mogu-gateway
  security:
    user:
      name: user
      password: password123
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8606
        username: user
        password: password123
        instance:
          service-base-url: http://localhost:8607
  cloud:
    gateway:
      discovery: #
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true # 使用小写服务名，默认是大写
      routes: # 配置路由规则
        - id: api-eureka
          uri: lb://mogu-eureka
          predicates:
            - Path=/api-eureka/**
        - id: api-monitor
          uri: lb://mogu-monitor
          predicates:
            - Path=/api-monitor/**
        - id: api-picture
          uri: lb://mogu-picture
          predicates:
            - Path=/api-picture/**
        - id: api-web
          uri: lb://mogu-web
          predicates:
            - Path=/api-web/**
        - id: api-admin
          uri: lb://mogu-admin
          predicates:
            - Path=/api-admin/**
        - id: api-sms
          uri: lb://mogu-sms
          predicates:
            - Path=/api-sms/**

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always